<?xml version="1.0" encoding="utf-8"?>
<!--

The purpose of this file is to transform WiX XML generated by heat.exe, the WiX "harvesting" tool. With the options we specify to heat
in the pre-build event for this project, we're going through the LogDoctor output directory and creating a WiX file that will install that
directory and its contents.

The problem is that heat.exe generates WiX code that isn't quite in the right format we want. For instance, we want to be able to include
the XML into the main Product.wxs file, but heat.exe doesn't generate an <Include> root element; instead it has a <wix> root element.
There are some other problems with the output from heat.exe.

The purpose of this file is to transforms the output of heat.exe so that it becomes usable for our project.

-->
<xsl:stylesheet version="2.0"
    xmlns:wix="http://schemas.microsoft.com/wix/2006/wi"
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    exclude-result-prefixes="wix">


  <xsl:output method="xml" indent="yes"/>

  <!-- Replace the Wix element with an Include element, since the file we're producing is going to be a wxi (WiX include) file -->
  <xsl:template match="wix:Wix">
    <xsl:element name="Include">
      <xsl:apply-templates select="@* | node()"/>
    </xsl:element>
  </xsl:template>

  <!-- This block of code passes through all elements that don't have special templates for them without changing them. -->
  <xsl:template match="@* | node()">
    <xsl:copy>
      <xsl:apply-templates select="@* | node()"/>
    </xsl:copy>
  </xsl:template>

  <!-- This removes the dist directory from the folder structure that the WiX installer will produce. This doesn't just remove 
       the offending element; it removes the offending element and promotes its children to the parent. This essentially makes
       the folder structure shallower. No files are removed by this element. -->
  <xsl:template match="wix:Directory[@Name = 'Release']">
    <xsl:apply-templates />
  </xsl:template>

  <!-- This removes the dist directory from the folder structure that the WiX installer will produce. This doesn't just remove 
       the offending element; it removes the offending element and promotes its children to the parent. This essentially makes
       the folder structure shallower. No files are removed by this element. -->
  <xsl:template match="wix:Directory[@Name = 'Debug']">
    <xsl:apply-templates />
  </xsl:template>

</xsl:stylesheet>
